version: '2'
services:
  jenkins:
    image: "jenkins"
    ports:
     - "8080:8080"
    networks:
      - demo
  sonarqube:
    image: "sonarqube"
    ports:
     - "9000:9000"
    networks:
      - demo
  tomcat:
    image: 'tutum/tomcat:6.0'
    ports:
      - 10000:8080
    environment:
      - TOMCAT_PASS=admin
    networks:
      - demo
networks: 
  demo:
